version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=EUROPE/Sofia
      - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - ck:/config
      - tr:/transcode
      - data:/data
  volumes:
       ck:
       tr:
       data:
  
