version: "2"
services:
  midori:
    image: aaguilar/midori
    environment:
      - AXIGEN_PRECONFIGURED=yes
      - AXIGEN_ADMIN_PASSWORD=unknownadmin
    ports:
      - 5901:5901
      - 5801:5801
